wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.16.0
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1700578463.742228
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 7
      - 13
      - 23
      - 38
      - 39
      4: 3.11.6
      5: 0.16.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: epoch/epoch
      6:
      - 3
    - 1: epoch/loss
      5: 1
      6:
      - 1
    - 1: epoch/mean_absolute_percentage_error
      5: 1
      6:
      - 1
    - 1: epoch/mean_absolute_error
      5: 1
      6:
      - 1
    - 1: epoch/val_loss
      5: 1
      6:
      - 1
    - 1: epoch/val_mean_absolute_percentage_error
      5: 1
      6:
      - 1
    - 1: epoch/val_mean_absolute_error
      5: 1
      6:
      - 1
    - 1: epoch/learning_rate
      5: 1
      6:
      - 1
sequence_length:
  desc: null
  value: 25
batch_size:
  desc: null
  value: 16
num_features:
  desc: null
  value: 8
horizon:
  desc: null
  value: 1
max_epochs:
  desc: null
  value: 100
dense_architecture:
  desc: null
  value: L3_U16
dense_layers:
  desc: null
  value: 3
dense_units:
  desc: null
  value: 16
loss:
  desc: null
  value: mean_squared_error
metric_mape:
  desc: null
  value: mean_absolute_percentage_error
metric_mae:
  desc: null
  value: mean_absolute_error
