wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.16.0
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1700571858.569863
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 19
      - 23
      4: 3.11.6
      5: 0.16.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
horizon:
  desc: null
  value: 1
max_epochs:
  desc: null
  value: 100
loss:
  desc: null
  value: <keras.src.losses.MeanSquaredError object at 0x00000230E215A450>
metrics:
  desc: null
  value:
  - RootMeanSquaredError(name=root_mean_squared_error,dtype=float32)
  - MeanAbsolutePercentageError(name=mean_absolute_percentage_error,dtype=float32)
  - MeanAbsoluteError(name=mean_absolute_error,dtype=float32)
early_stopping:
  desc: null
  value: <keras.src.callbacks.EarlyStopping object at 0x00000230E20DD5D0>
timing_callback:
  desc: null
  value: <__main__.TimingCallback object at 0x00000230E22D76D0>
custom_callback:
  desc: null
  value: <__main__.CustomCallback object at 0x00000230E22D76D0>
dense_architecture:
  desc: null
  value: L3_U16
dense_layers:
  desc: null
  value: 3
dense_units:
  desc: null
  value: 16
sequence_length:
  desc: null
  value: 25
batch_size:
  desc: null
  value: 16
num_features:
  desc: null
  value: 8
